"use client";
import {useLanguage} from "@/components/language-provider";
import {MessageCircle,Menu,X,MapPin,ShieldCheck,Sparkles,Handshake} from "lucide-react";
import {useState} from "react";
import Image from "next/image";
export function Site(){const{lang,setLang,t}=useLanguage();const[open,setOpen]=useState(false);const nav=[[t.home,"#"],[t.story,"#story"],[t.honey,"#honey"],[t.values,"#values"],[t.gallery,"#gallery"],[t.contact,"#contact"]];return <><header className="sticky top-0 z-50 border-b border-[#ded6ca] bg-[#fbf8f1]/95 backdrop-blur"><div className="wrap flex h-16 items-center justify-between"><a className="flex items-center gap-2" href="#" aria-label="IGGOULFANE home"><Image src="/iggoulfane-logo.jpeg" alt="IGGOULFANE - تعاونية العسل" width={46} height={46} className="h-11 w-11 rounded-full object-cover"/><span className="display hidden text-lg tracking-[.12em] sm:inline">IGGOULFANE</span></a><nav className="hidden md:flex gap-6 text-[10px] uppercase tracking-widest">{nav.map(([x,h])=><a key={h} href={h}>{x}</a>)}</nav><div className="flex items-center gap-3"><div className="flex gap-2 text-[10px]">{(["en","fr","ar"] as const).map(l=><button key={l} onClick={()=>setLang(l)} className={lang===l?"font-bold text-[#b85c22]":""}>{l.toUpperCase()}</button>)}</div><a className="btn btn-amber hidden lg:inline-flex" href="#contact"><MessageCircle size={14}/>{t.order}</a><button className="md:hidden" aria-label="Menu" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button></div></div>{open&&<nav className="wrap grid gap-1 border-t border-[#ded6ca] py-3 md:hidden">{nav.map(([x,h])=><a onClick={()=>setOpen(false)} className="py-2 text-sm" key={h} href={h}>{x}</a>)}<a onClick={()=>setOpen(false)} className="btn btn-amber mt-2" href="#contact"><MessageCircle size={14}/>{t.order}</a></nav>}</header><main>
<section className="section"><div className="wrap grid items-center gap-12 md:grid-cols-2"><div><p className="eyebrow">{t.eyebrow} · تعاونية مغربية</p><h1 className="display mt-4 text-5xl leading-[.98] md:text-7xl">{t.hero1}<br/><i>{t.hero2}</i></h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#6f6258]">{t.heroText}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#honey" className="btn btn-dark">{t.discover} ↓</a><a href="#contact" className="btn"><MessageCircle size={14}/>{t.order}</a></div></div><div className="photo photo-hero mx-auto aspect-[4/5] w-full max-w-md rounded-t-[42%] shadow-xl"><div className="absolute bottom-5 left-5 z-10 bg-[#fbf8f1] p-4"><span className="eyebrow">{t.eyebrow}</span><div className="display text-xl">{t.productTitle}</div></div></div></div></section>
<section id="story" className="section bg-[#f3eee5]"><div className="wrap grid gap-12 md:grid-cols-2"><div><p className="eyebrow">{t.story}</p><h2 className="display mt-3 text-4xl md:text-5xl">{t.storyTitle}</h2><p className="mt-5 text-sm leading-7 text-[#6f6258]">{t.storyText}</p></div><div className="photo photo-story min-h-[390px] rounded-t-[120px]"/></div></section>
<section id="honey" className="section"><div className="wrap"><div className="text-center"><p className="eyebrow">{t.honey}</p><h2 className="display mt-2 text-4xl">{t.productTitle}</h2></div><div className="card mt-10 grid gap-10 p-6 md:grid-cols-2 md:p-12"><div className="photo photo-product aspect-square rounded-t-[96px]"/><div className="self-center"><p className="eyebrow">{t.eyebrow}</p><h3 className="display mt-2 text-3xl">{t.productTitle}</h3><p className="mt-5 text-sm leading-7 text-[#6f6258]">{t.productText}</p><a href="#contact" className="btn btn-amber mt-7"><MessageCircle size={14}/>{t.order}</a></div></div></div></section>
<section id="values" className="section bg-[#ebe7df]"><div className="wrap text-center"><p className="eyebrow">{t.values}</p><h2 className="display mt-2 text-4xl">{t.why}</h2><div className="mt-10 grid gap-3 md:grid-cols-4">{[t.value1,t.value2,t.value3,t.value4].map((x,i)=>{const Icon=[MapPin,Sparkles,ShieldCheck,Handshake][i];return <div className="card group p-7 transition duration-300 hover:-translate-y-1 hover:shadow-lg" key={x}><div className="mx-auto mb-5 flex h-10 w-10 items-center justify-center rounded-full border border-[#d9c9b8] text-[#a34d17]"><Icon size={17}/></div><h3 className="display text-xl">{x}</h3></div>})}</div></div></section>
<section id="gallery" className="section"><div className="wrap text-center"><p className="eyebrow">{t.gallery}</p><h2 className="display mt-2 text-4xl">{t.gallery}</h2><p className="mt-3 text-sm text-[#75685f]">{t.galleryText}</p><div className="mt-9 grid gap-3 md:grid-cols-12"><div className="photo photo-gallery-a aspect-[4/5] md:col-span-5"/><div className="photo photo-gallery-b aspect-[4/5] md:col-span-3 md:mt-16"/><div className="photo photo-gallery-c aspect-[4/5] md:col-span-4"/></div></div></section>
<section id="contact" className="section bg-[#f3eee5]"><div className="wrap"><div className="card mx-auto flex max-w-4xl flex-col gap-8 p-8 md:flex-row md:items-center md:justify-between md:p-12"><div><p className="eyebrow">{t.contact}</p><h2 className="display mt-2 text-4xl">{t.cta}</h2><p className="mt-3 max-w-xl text-sm text-[#75685f]">{t.ctaText}</p></div><button className="btn btn-amber whitespace-nowrap opacity-70" type="button" aria-disabled="true" title="WhatsApp number will be added after confirmation"><MessageCircle size={15}/>{t.order}</button></div></div></section></main>
<footer className="bg-[#201b18] py-14 text-[#f7f1e8]"><div className="wrap"><div className="flex items-center gap-3"><Image src="/iggoulfane-logo.jpeg" alt="IGGOULFANE - تعاونية العسل" width={70} height={70} className="h-[70px] w-[70px] rounded-full object-cover"/><div><div className="display text-2xl tracking-widest">IGGOULFANE</div><div className="mt-1 text-xs text-[#d7b36a]">تعاونية العسل</div></div></div><p className="mt-4 max-w-xl text-xs leading-6 text-[#c8beb4]">{t.heroText}</p><div className="mt-10 border-t border-white/10 pt-6 text-[10px] text-[#9f958c]">© IGGOULFANE. All rights reserved.</div></div></footer></>}