"use client";
import {useLanguage} from "@/components/language-provider";
import {MessageCircle,Menu} from "lucide-react";
export function Site(){const{lang,setLang,t}=useLanguage();const nav=[[t.home,"#"],[t.story,"#story"],[t.honey,"#honey"],[t.values,"#values"],[t.gallery,"#gallery"],[t.contact,"#contact"]];return <><header className="sticky top-0 z-50 border-b border-[#ded6ca] bg-[#fbf8f1]/95 backdrop-blur"><div className="wrap flex h-16 items-center justify-between"><a className="display text-xl tracking-[.12em]" href="#">IGGOULFANE</a><nav className="hidden md:flex gap-6 text-[10px] uppercase tracking-widest">{nav.map(([x,h])=><a key={h} href={h}>{x}</a>)}</nav><div className="flex items-center gap-3"><div className="flex gap-2 text-[10px]">{(["en","fr","ar"] as const).map(l=><button key={l} onClick={()=>setLang(l)} className={lang===l?"font-bold text-[#b85c22]":""}>{l.toUpperCase()}</button>)}</div><a className="btn btn-amber hidden lg:inline-flex" href="#contact"><MessageCircle size={14}/>{t.order}</a><Menu className="md:hidden" size={20}/></div></div></header><main>
<section className="section"><div className="wrap grid items-center gap-12 md:grid-cols-2"><div><p className="eyebrow">{t.eyebrow} · تعاونية مغربية</p><h1 className="display mt-4 text-5xl leading-[.98] md:text-7xl">{t.hero1}<br/><i>{t.hero2}</i></h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#6f6258]">{t.heroText}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#honey" className="btn btn-dark">{t.discover} ↓</a><a href="#contact" className="btn"><MessageCircle size={14}/>{t.order}</a></div></div><div className="photo mx-auto aspect-[4/5] w-full max-w-md rounded-t-[42%] shadow-xl"><div className="absolute bottom-5 left-5 z-10 bg-[#fbf8f1] p-4"><span className="eyebrow">{t.eyebrow}</span><div className="display text-xl">{t.productTitle}</div></div></div></div></section>
<section id="story" className="section bg-[#f3eee5]"><div className="wrap grid gap-12 md:grid-cols-2"><div><p className="eyebrow">{t.story}</p><h2 className="display mt-3 text-4xl md:text-5xl">{t.storyTitle}</h2><p className="mt-5 text-sm leading-7 text-[#6f6258]">{t.storyText}</p></div><div className="photo min-h-[390px]"/></div></section>
<section id="honey" className="section"><div className="wrap"><div className="text-center"><p className="eyebrow">{t.honey}</p><h2 className="display mt-2 text-4xl">{t.productTitle}</h2></div><div className="card mt-10 grid gap-10 p-6 md:grid-cols-2 md:p-12"><div className="photo aspect-square"/><div className="self-center"><p className="eyebrow">{t.eyebrow}</p><h3 className="display mt-2 text-3xl">{t.productTitle}</h3><p className="mt-5 text-sm leading-7 text-[#6f6258]">{t.productText}</p><a href="#contact" className="btn btn-amber mt-7"><MessageCircle size={14}/>{t.order}</a></div></div></div></section>
<section id="values" className="section bg-[#ebe7df]"><div className="wrap text-center"><p className="eyebrow">{t.values}</p><h2 className="display mt-2 text-4xl">{t.why}</h2><div className="mt-10 grid gap-3 md:grid-cols-4">{["Moroccan Cooperative","Craft & Know-How","Care & Attention","Direct Contact"].map(x=><div className="card p-7" key={x}><h3 className="display text-xl">{x}</h3></div>)}</div></div></section>
<section id="gallery" className="section"><div className="wrap text-center"><p className="eyebrow">{t.gallery}</p><h2 className="display mt-2 text-4xl">{t.gallery}</h2><p className="mt-3 text-sm text-[#75685f]">{t.galleryText}</p><div className="mt-9 grid gap-3 md:grid-cols-3"><div className="photo aspect-[4/5]"/><div className="photo aspect-[4/5]"/><div className="photo aspect-[4/5]"/></div></div></section>
<section id="contact" className="section bg-[#f3eee5]"><div className="wrap"><div className="card mx-auto flex max-w-4xl flex-col gap-8 p-8 md:flex-row md:items-center md:justify-between md:p-12"><div><p className="eyebrow">{t.contact}</p><h2 className="display mt-2 text-4xl">{t.cta}</h2><p className="mt-3 max-w-xl text-sm text-[#75685f]">{t.ctaText}</p></div><button className="btn btn-amber whitespace-nowrap"><MessageCircle size={15}/>{t.order}</button></div></div></section></main>
<footer className="bg-[#201b18] py-14 text-[#f7f1e8]"><div className="wrap"><div className="display text-2xl tracking-widest">IGGOULFANE</div><p className="mt-4 text-xs text-[#c8beb4]">{t.heroText}</p><div className="mt-10 border-t border-white/10 pt-6 text-[10px] text-[#9f958c]">© IGGOULFANE. All rights reserved.</div></div></footer></>}